#!/bin/bash
# setup_cron.sh
# ─────────────
# Installs a @reboot cron job to run the full dashboard rebuild
# whenever the computer starts up.
#
# Run once:
#   chmod +x setup_cron.sh && ./setup_cron.sh

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LOG_FILE="$SCRIPT_DIR/cron.log"

# Wait 60s for network to come up, then run rebuild
CRON_LINE="@reboot sleep 60 && cd $SCRIPT_DIR && $SCRIPT_DIR/.venv/bin/python3 -m bash_wrapper 2>&1 | tee -a $LOG_FILE"

# Simpler and more reliable — use a wrapper script
WRAPPER="$SCRIPT_DIR/run_on_startup.sh"

cat > "$WRAPPER" << WRAPPER_EOF
#!/bin/bash
# Auto-generated by setup_cron.sh — runs dashboard rebuild on startup
sleep 60   # wait for network
cd "$SCRIPT_DIR"
source "$SCRIPT_DIR/.venv/bin/activate"
echo "=== Startup rebuild \$(date) ===" >> "$LOG_FILE"
python3 icu_download.py >> "$LOG_FILE" 2>&1
./rebuild_all.sh --push >> "$LOG_FILE" 2>&1
echo "=== Done \$(date) ===" >> "$LOG_FILE"
WRAPPER_EOF

chmod +x "$WRAPPER"

# Install @reboot cron entry
CRON_LINE="@reboot $WRAPPER"

if crontab -l 2>/dev/null | grep -q "run_on_startup"; then
    echo "Startup cron job already installed:"
    crontab -l | grep "run_on_startup"
    exit 0
fi

( crontab -l 2>/dev/null; echo "$CRON_LINE" ) | crontab -

echo "✓ Startup cron job installed."
echo "  Script : $WRAPPER"
echo "  Log    : $LOG_FILE"
echo ""
echo "To verify:  crontab -l"
echo "To remove:  crontab -l | grep -v run_on_startup | crontab -"
echo "To test:    $WRAPPER &"
